"""Initial migration

Revision ID: 341061c89b89
Revises: 
Create Date: 2025-05-20 21:44:38.445190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341061c89b89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_beg', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_station', sa.Integer(), nullable=False),
    sa.Column('name_station', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_station')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_train', sa.Integer(), nullable=False),
    sa.Column('station_from', sa.Integer(), nullable=False),
    sa.Column('station_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_from'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['station_to'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_table('period_trains',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('period_id', 'train_id')
    )
    op.create_table('train_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_train', sa.Integer(), nullable=False),
    sa.Column('num_order', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('hours_arr', sa.Integer(), nullable=True),
    sa.Column('minutes_arr', sa.Integer(), nullable=True),
    sa.Column('hours_depart', sa.Integer(), nullable=True),
    sa.Column('minutes_depart', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_train'], ['trains.id'], ),
    sa.ForeignKeyConstraint(['station'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_route_id'), 'train_route', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_route_id'), table_name='train_route')
    op.drop_table('train_route')
    op.drop_table('period_trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_table('periods')
    # ### end Alembic commands ###
