# Generated by Django 5.2 on 2025-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameShort', models.CharField(max_length=20)),
                ('nameFull', models.CharField(max_length=60)),
            ],
        ),
    ]
