# Generated by Django 5.2 on 2025-05-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('idGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLesson', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=150)),
                ('maxGrade', models.PositiveSmallIntegerField(blank=True)),
                ('idJournal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
                ('idSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.subject')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=25)),
                ('role', models.BooleanField()),
                ('idGroup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journal.group')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresence', models.BooleanField(default=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True)),
                ('idLesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson')),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.user')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='idTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='journal.user'),
        ),
    ]
