# Generated by Django 5.2 on 2025-05-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_group_journal_lesson_user_rating_lesson_idteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='maxGrade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='idGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.group'),
        ),
    ]
